### ISSUE TITLE
Why not use png?

### ISSUE THREAD

**Issue by joaofreires** [jonesmartins/pycrusher#1]
Just use jpg compression lose quality and alpha values. It may be good to use more than one format.

**Comment by jonesmartins** [comment]
What do you mean? Have the output be .png as well?

**Comment by joaofreires** [comment]
Well, suppose you want to pycrusher you weblogo, you have a layer of transparency, so it would be interesting to keep. I don't read your code! I just saw the output in jpg format. 
I loved the idea, if I have a website I will use it to put it on a maintenance logo.

**Comment by jonesmartins** [comment]
So what you're saying is that if your input is a .png file, you want your pycrusher output with the same levels of transparency? That's a great idea.

**Comment by joaofreires** [comment]
I think the idea is to just keep the type of compression, and not make changes to the alpha channel.

**Comment by jonesmartins** [comment]
Great, I'll try to implement that. :D
