### ISSUE TITLE
Error on OSX: "ImportError: 'module' object has no attribute 'main'"

### ISSUE THREAD

**Issue by subzerofun** [jonesmartins/pycrusher#1]
I tried the pip and manual installing setup, but everytime i run pycrusher i get this error:

```
pycrusher --help
Traceback (most recent call last):
  File "/usr/local/bin/pycrusher", line 11, in <module>
    load_entry_point('pycrusher==0.3.5', 'console_scripts', 'pycrusher')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2312, in resolve
    raise ImportError(str(exc))
ImportError: 'module' object has no attribute 'main'
```

**Comment by jonesmartins** [comment]
I didn't test the installation on OSX but I did get an ImportError sometimes, which was solved by manual pip installation. I'll definitely try and fix that. Thanks!

**Comment by jonesmartins** [comment]
@subzerofun Could you please try installing it again and tell me if it worked? :)

**Comment by subzerofun** [comment]
Thanks for the quick update! I can now run `pycrusher -h` without getting the import error.

But... Converting doesn't work, i get another error:

```
$pycrusher -i 15 -o test-pycrusher.jpg test.jpg
Traceback (most recent call last):
  File "/usr/local/bin/pycrusher", line 11, in <module>
    load_entry_point('pycrusher==0.3.6', 'console_scripts', 'pycrusher')()
  File "build/bdist.macosx-10.12-x86_64/egg/pycrusher/__main__.py", line 7, in main
AttributeError: 'module' object has no attribute 'make_dir'
```

I checked the file path and tried adding the whole folder path to the files, but i always get the same error.

**Comment by jonesmartins** [comment]
I forgot to test the most important part! Turns out I tried to organize the main code and forgot to import stuff correctly. I think it works properly now.

**Comment by subzerofun** [comment]
Looks like its working fine now – thanks!
![pycrusher](https://cloud.githubusercontent.com/assets/17863119/23829106/22df1048-06e8-11e7-8867-b63b73c71c26.png)

PS: I should take a smaller iteration value the next time 😅

**Comment by jonesmartins** [comment]
Thanks so much for pointing out the bug. 
Also, the bar addapts to the terminal size so it does happen to get very wide. 
I'm very glad it works for you now. I hope you enjoy it! :)

**Comment by subzerofun** [comment]
Yeah thanks – i will keep this tool ready for the next time when one of those "blocky jpeg" threads start on reddit (the ones where someone posts a decently compressed jpg until everything spirals out of control and every other user reposts the same image – every time with more jpg goodness).

**Comment by jonesmartins** [comment]
Hahahaha, that's great!
The idea for pycrusher came when I wanted to simulate those terrible meme screenshots people take on Instagram, Twitter and such. Spiralling out of control is exactly what made me automate it. 
Also, if you want a blockier output, run it with the -r flag. I got my profile picture with a setup of `-r -c 0`  and about 40 iterations.
